### ISSUE TITLE
Could not Compile delphi

### ISSUE THREAD

**Issue by jxzeng-git** [mc2-project/delphi#25]
I encountered the following issue in testing my build of Delphi:
`RUST_BACKTRACE=1 cargo +nightly test`

Sometimes, executing this yields the following error:

```
failures:

---- tests::gc::test_gc_relu stdout ----
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `42`,
 right: `84`', /root/.cargo/git/checkouts/fancy-garbling-c4933c013ff259da/848216e/src/static.rs:273:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:182:5
   4: fancy_garbling::static::Encoder::encode_garbler_inputs
             at /root/.cargo/git/checkouts/fancy-garbling-c4933c013ff259da/848216e/src/static.rs:273:9
   5: protocols::gc::ReluProtocol<P>::online_server_protocol::{{closure}}
             at ./src/gc.rs:257:42
   6: core::iter::adapters::map::map_fold::{{closure}}
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/iter/adapters/map.rs:84:28
   7: core::iter::traits::iterator::Iterator::fold
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/iter/traits/iterator.rs:2285:21
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/iter/adapters/map.rs:124:9
   9: core::iter::traits::iterator::Iterator::for_each
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/iter/traits/iterator.rs:773:9
  10: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/alloc/src/vec/spec_extend.rs:40:17
  11: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/alloc/src/vec/spec_from_iter_nested.rs:62:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/alloc/src/vec/spec_from_iter.rs:33:9
  13: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/alloc/src/vec/mod.rs:2552:9
  14: core::iter::traits::iterator::Iterator::collect
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/iter/traits/iterator.rs:1778:9
  15: protocols::gc::ReluProtocol<P>::online_server_protocol
             at ./src/gc.rs:250:21
  16: protocols::tests::gc::test_gc_relu::{{closure}}::{{closure}}
             at ./src/tests.rs:290:21
  17: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:415:31
  18: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:423:39
  19: <alloc::boxed::Box<F,A> as core::ops::function::FnMut<Args>>::call_mut
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/alloc/src/boxed.rs:1861:9
  20: crossbeam_utils::thread::ScopedThreadBuilder::spawn::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:431:44
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'tests::gc::test_gc_relu' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', protocols/src/tests.rs:297:18
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/result.rs:1065:23
   4: protocols::tests::gc::test_gc_relu::{{closure}}
             at ./src/tests.rs:285:21
   5: crossbeam_utils::thread::scope::{{closure}}
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:161:65
   6: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panic/unwind_safe.rs:271:9
   7: std::panicking::try::do_call
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:492:40
   8: std::panicking::try
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:456:19
   9: std::panic::catch_unwind
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panic.rs:137:14
  10: crossbeam_utils::thread::scope
             at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.7.2/src/thread.rs:161:18
  11: protocols::tests::gc::test_gc_relu
             at ./src/tests.rs:263:29
  12: core::ops::function::FnOnce::call_once
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/ops/function.rs:227:5
```

Other times, executing this yields the other one error:
```
failures:

---- gc::test::test_relu stdout ----
n=42 q=2 Q=4398046511104
computation info:
  garbler inputs:                  126 // communication: 16.13 Kb
  evaluator inputs:                  0 // communication: 0.00 Kb
  reused values:                     0
  outputs:                          42
  output ciphertexts:               84 // communication: 10.75 Kb
  constants:                         2 // communication: 0.26 Kb
  additions:                       920
  subtractions:                      0
  cmuls:                             0
  projections:                       0
  multiplications:                 292
  ciphertexts:                     584 // communication: 0.07 Mb (74.75 Kb)
  total communication:         0.10 Mb
  wire moduli: {
    2: 1214,
}
thread 'gc::test::test_relu' panicked at 'assertion failed: `(left == right)`
  left: `1897718357985`,
 right: `1897718357984`: Iteration 7003, Pre-ReLU value is 0.0009765625, value should be 0, FixedPoint { inner: Fp64(0), num_muls: 0 }', crypto-primitives/src/gc.rs:279:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/panicking.rs:182:5
   4: crypto_primitives::gc::test::test_relu
             at ./src/gc.rs:279:13
   5: core::ops::function::FnOnce::call_once
             at /rustc/d3ad51b48f83329fac0cd8a9f1253f3146613c1c/library/core/src/ops/function.rs:227:5
```

This was executed in Ubuntu 18.04.6 using Cargo/Rust rustc 1.59.0 (9d1b2106e 2022-02-23)

Any insights on this issue?

Thanks!

**Comment by ryanleh** [comment]
Hi @jxzeng-git, this off-by-one is a known issue with the ReLU tests. I believe the problem is actually just with how the test is structured but, even if it really is a problem with our implementation, it has a negligible impact on accuracy so I haven't invested the time to investigate further. You can safely ignore it 😁 I will remove this test soon to avoid future confusion.

**Comment by jxzeng-git** [comment]
😁 Got it, thanks a lot!

**Comment by tolusophy** [comment]
I'm getting the following error! 

`cargo +nightly build --release
   Compiling algebra v0.1.0 (/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/algebra)
   Compiling protocols-sys v0.1.0 (/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/protocols-sys)
error: failed to run custom build command for `protocols-sys v0.1.0 (/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/protocols-sys)`

Caused by:
  process didn't exit successfully: `/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/target/release/build/protocols-sys-5e9b98424d734692/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/protocols-sys/c++" "-DUNITTESTS=0" "-DCMAKE_INSTALL_PREFIX=/home/toluwani/Documents/PolyKervnet/Delphi/delphi/rust/target/release/build/protocols-sys-af4aedd01d58be0e/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=RelWithDebInfo"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /home/toluwani/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.48/src/lib.rs:975:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: the feature `const_fn_trait_bound` has been stable since 1.61.0 and no longer requires an attribute to enable
  --> algebra/src/lib.rs:28:12
   |
28 | #![feature(const_fn_trait_bound)]
   |            ^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> algebra/src/lib.rs:16:5
   |
16 |     stable_features,
   |     ^^^^^^^^^^^^^^^

error: could not compile `algebra` due to previous error`

What could be the issue here?

**Comment by ryanleh** [comment]
From the logs you provided:
> --- stderr
thread 'main' panicked at '
failed to execute command: No such file or directory (os error 2)
is cmake not installed?

Could you ensure `cmake` is installed? (Also in the future try to open a new issue since this one was closed + unrelated to the error you experienced)

**Comment by tolusophy** [comment]
Thank you @ryanleh 
I found out I had an older version of cmake, so I installed the 23.2 version.

Thank you
