### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by llCurious** [mc2-project/delphi#4]
(pid=51090) 2021-01-14 04:31:36.949779: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /home/delphi/python/minionn/pretrained/relu/model: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

**Comment by llCurious** [comment]
All the pre-install requirements are fulfilled and i execute the model preprocessing command: python minionn/minionn_cifar10.py -n 7_layers -d /tmp -a 7 -r minionn/pretrained/relu/model 
. It showed the above error. Is the package error or something?

**Comment by ryanleh** [comment]
Hello,
Apologies for the very slow response - for some reason I never saw a notification for this issue.

I reran the line in question on a new Ubuntu 20.04 machine with Python3.7 and it appears that the error you're seeing is due to a worker thread error:
```
2021-04-25 05:02:08,537 ERROR trial_runner.py:482 -- Error processing event.                                                                                                                                        
Traceback (most recent call last):                                                                                                                                                                                  
  File "/usr/local/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 426, in _process_trial                                                                                                               
    result = self.trial_executor.fetch_result(trial)                                                                                                                                                                
  File "/usr/local/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 378, in fetch_result                                                                                                           
    result = ray.get(trial_future[0], DEFAULT_GET_TIMEOUT)                                                                                                                                                          
  File "/usr/local/lib/python3.7/site-packages/ray/worker.py", line 1457, in get                                                                                                                                    
    raise value.as_instanceof_cause()                                                                                                                                                                               
ray.exceptions.RayTaskError(AttributeError): ray_worker (pid=61357, ip=172.31.39.201)                                                                                                                               
  File "python/ray/_raylet.pyx", line 626, in ray._raylet.execute_task                                                                                                                                                File "python/ray/_raylet.pyx", line 633, in ray._raylet.execute_task                                                                                                                                              
  File "python/ray/_raylet.pyx", line 634, in ray._raylet.execute_task                                                                                                                                              
  File "python/ray/_raylet.pyx", line 636, in ray._raylet.execute_task                                                                                                                                                File "python/ray/_raylet.pyx", line 619, in ray._raylet.execute_task.function_executor                                                                                                                            
  File "/usr/local/lib/python3.7/site-packages/ray/tune/trainable.py", line 96, in __init__                                                                                                                         
    self._setup(copy.deepcopy(self.config))                                                                                                                                                                         
  File "minionn/minionn_cifar10.py", line 174, in _setup                                                                                                                                                                self._restore(self.restore_path)                                                                                                                                                                                
  File "minionn/minionn_cifar10.py", line 277, in _restore                                                                                                                                                          
    self.model.load_weights(path)                                                                         
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 182, in load_weights
    return super(Model, self).load_weights(filepath, by_name)                                             
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1373, in load_weights                                                                                              saving.load_weights_from_hdf5_group(f, self.layers)                                                   
  File "/usr/local/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 645, in load_weights_from_hdf5_group
    original_keras_version = f.attrs['keras_version'].decode('utf8')                                      
AttributeError: 'str' object has no attribute 'decode'                    
```
which then causes some issues with trying to reload the serialized model. This appears to be an issue with the `h5py` package as explained [here](https://stackoverflow.com/questions/64795784/google-ai-platform-unexpected-error-when-loading-the-model-str-object-has-no). Following the instructions given in the answer fixed the error for me i.e. run the following:

`pip uninstall -y h5py`
and then
`pip install 'h5py < 3.0.0'`
